version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/velosmithnodeapp

hooks:
  ApplicationStop:
    - location: stop-app
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: start-app
      timeout: 300
      runas: ubuntu
